// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: cootek.pgd.ysession.proto

package ysession

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	account "weather_mgr/cootek/pgd/account"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SessionParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account        *account.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	RequestId      string           `protobuf:"bytes,2,opt,name=requestId,proto3" json:"requestId,omitempty"`
	PreSpanId      string           `protobuf:"bytes,3,opt,name=preSpanId,proto3" json:"preSpanId,omitempty"`
	CurSpanId      int64            `protobuf:"varint,4,opt,name=curSpanId,proto3" json:"curSpanId,omitempty"`
	SendTsMillisec int64            `protobuf:"varint,5,opt,name=sendTsMillisec,proto3" json:"sendTsMillisec,omitempty"`
}

func (x *SessionParam) Reset() {
	*x = SessionParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cootek_pgd_ysession_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionParam) ProtoMessage() {}

func (x *SessionParam) ProtoReflect() protoreflect.Message {
	mi := &file_cootek_pgd_ysession_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionParam.ProtoReflect.Descriptor instead.
func (*SessionParam) Descriptor() ([]byte, []int) {
	return file_cootek_pgd_ysession_proto_rawDescGZIP(), []int{0}
}

func (x *SessionParam) GetAccount() *account.Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *SessionParam) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SessionParam) GetPreSpanId() string {
	if x != nil {
		return x.PreSpanId
	}
	return ""
}

func (x *SessionParam) GetCurSpanId() int64 {
	if x != nil {
		return x.CurSpanId
	}
	return 0
}

func (x *SessionParam) GetSendTsMillisec() int64 {
	if x != nil {
		return x.SendTsMillisec
	}
	return 0
}

var File_cootek_pgd_ysession_proto protoreflect.FileDescriptor

var file_cootek_pgd_ysession_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6f, 0x74, 0x65, 0x6b, 0x2e, 0x70, 0x67, 0x64, 0x2e, 0x79, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x6f, 0x6f,
	0x74, 0x65, 0x6b, 0x2e, 0x70, 0x67, 0x64, 0x2e, 0x79, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x1a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xc7, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x12, 0x35, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6f, 0x74, 0x65, 0x6b, 0x2e, 0x70, 0x67, 0x64, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x53, 0x70, 0x61, 0x6e,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x65, 0x53, 0x70, 0x61,
	0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x53, 0x70, 0x61, 0x6e, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x75, 0x72, 0x53, 0x70, 0x61, 0x6e, 0x49,
	0x64, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x73, 0x4d, 0x69, 0x6c, 0x6c, 0x69,
	0x73, 0x65, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x54,
	0x73, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x42, 0x1f, 0x5a, 0x1d, 0x63, 0x6f, 0x69,
	0x6e, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x63, 0x6f, 0x6f, 0x74, 0x65, 0x6b, 0x2f, 0x70, 0x67,
	0x64, 0x2f, 0x79, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_cootek_pgd_ysession_proto_rawDescOnce sync.Once
	file_cootek_pgd_ysession_proto_rawDescData = file_cootek_pgd_ysession_proto_rawDesc
)

func file_cootek_pgd_ysession_proto_rawDescGZIP() []byte {
	file_cootek_pgd_ysession_proto_rawDescOnce.Do(func() {
		file_cootek_pgd_ysession_proto_rawDescData = protoimpl.X.CompressGZIP(file_cootek_pgd_ysession_proto_rawDescData)
	})
	return file_cootek_pgd_ysession_proto_rawDescData
}

var file_cootek_pgd_ysession_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cootek_pgd_ysession_proto_goTypes = []interface{}{
	(*SessionParam)(nil),    // 0: cootek.pgd.ysession.SessionParam
	(*account.Account)(nil), // 1: cootek.pgd.account.Account
}
var file_cootek_pgd_ysession_proto_depIdxs = []int32{
	1, // 0: cootek.pgd.ysession.SessionParam.account:type_name -> cootek.pgd.account.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cootek_pgd_ysession_proto_init() }
func file_cootek_pgd_ysession_proto_init() {
	if File_cootek_pgd_ysession_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cootek_pgd_ysession_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cootek_pgd_ysession_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cootek_pgd_ysession_proto_goTypes,
		DependencyIndexes: file_cootek_pgd_ysession_proto_depIdxs,
		MessageInfos:      file_cootek_pgd_ysession_proto_msgTypes,
	}.Build()
	File_cootek_pgd_ysession_proto = out.File
	file_cootek_pgd_ysession_proto_rawDesc = nil
	file_cootek_pgd_ysession_proto_goTypes = nil
	file_cootek_pgd_ysession_proto_depIdxs = nil
}
