name = "base"
current_env = "pro"
location = "cn"

[app]
    aesKey = "dea5a27becaa2e054b959b3b7c8c95034949e4ab"

[log]
    level=-1
    development=false
    outputPaths=["/ssd/base-prd-cn-api.log"]

[redis]
    [redis.local]
        addr = "127.0.0.1:6379"
        password = ""
        db = 0
        maxRetries = 64
        poolSize=10
        minIdleConns=5
        dialTimeout = 300
        readTimeout = 500
        writeTimeout = 500

[db]
    [db.local]
        dsn = "root:123456@tcp(127.0.0.1:3306)/withdraw?timeout=10s&readTimeout=10s&writeTimeout=10s&parseTime=true&loc=Local&charset=utf8"
        active = 50
        idle = 25