// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cootek.pgd.base.account.proto

package account

import (
	account "base/cootek/pgd/account"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountInfoParam struct {
	Account              *account.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccountInfoParam) Reset()         { *m = AccountInfoParam{} }
func (m *AccountInfoParam) String() string { return proto.CompactTextString(m) }
func (*AccountInfoParam) ProtoMessage()    {}
func (*AccountInfoParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc2ddf47808c4d6, []int{0}
}

func (m *AccountInfoParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfoParam.Unmarshal(m, b)
}
func (m *AccountInfoParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfoParam.Marshal(b, m, deterministic)
}
func (m *AccountInfoParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfoParam.Merge(m, src)
}
func (m *AccountInfoParam) XXX_Size() int {
	return xxx_messageInfo_AccountInfoParam.Size(m)
}
func (m *AccountInfoParam) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfoParam.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfoParam proto.InternalMessageInfo

func (m *AccountInfoParam) GetAccount() *account.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type AccountInfoResult struct {
	ErrorCode            uint64                  `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Msg                  string                  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TimeUnix             int64                   `protobuf:"varint,3,opt,name=time_unix,json=timeUnix,proto3" json:"time_unix,omitempty"`
	Data                 *AccountInfoResult_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *AccountInfoResult) Reset()         { *m = AccountInfoResult{} }
func (m *AccountInfoResult) String() string { return proto.CompactTextString(m) }
func (*AccountInfoResult) ProtoMessage()    {}
func (*AccountInfoResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc2ddf47808c4d6, []int{1}
}

func (m *AccountInfoResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfoResult.Unmarshal(m, b)
}
func (m *AccountInfoResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfoResult.Marshal(b, m, deterministic)
}
func (m *AccountInfoResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfoResult.Merge(m, src)
}
func (m *AccountInfoResult) XXX_Size() int {
	return xxx_messageInfo_AccountInfoResult.Size(m)
}
func (m *AccountInfoResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfoResult.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfoResult proto.InternalMessageInfo

func (m *AccountInfoResult) GetErrorCode() uint64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *AccountInfoResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AccountInfoResult) GetTimeUnix() int64 {
	if m != nil {
		return m.TimeUnix
	}
	return 0
}

func (m *AccountInfoResult) GetData() *AccountInfoResult_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type AccountInfoResult_Data struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	TicketNum            int64    `protobuf:"varint,2,opt,name=ticket_num,json=ticketNum,proto3" json:"ticket_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfoResult_Data) Reset()         { *m = AccountInfoResult_Data{} }
func (m *AccountInfoResult_Data) String() string { return proto.CompactTextString(m) }
func (*AccountInfoResult_Data) ProtoMessage()    {}
func (*AccountInfoResult_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc2ddf47808c4d6, []int{1, 0}
}

func (m *AccountInfoResult_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfoResult_Data.Unmarshal(m, b)
}
func (m *AccountInfoResult_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfoResult_Data.Marshal(b, m, deterministic)
}
func (m *AccountInfoResult_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfoResult_Data.Merge(m, src)
}
func (m *AccountInfoResult_Data) XXX_Size() int {
	return xxx_messageInfo_AccountInfoResult_Data.Size(m)
}
func (m *AccountInfoResult_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfoResult_Data.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfoResult_Data proto.InternalMessageInfo

func (m *AccountInfoResult_Data) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AccountInfoResult_Data) GetTicketNum() int64 {
	if m != nil {
		return m.TicketNum
	}
	return 0
}

type IncrAmountParam struct {
	Account              *account.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	IncrNum              int64            `protobuf:"varint,2,opt,name=incr_num,json=incrNum,proto3" json:"incr_num,omitempty"`
	Event                string           `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IncrAmountParam) Reset()         { *m = IncrAmountParam{} }
func (m *IncrAmountParam) String() string { return proto.CompactTextString(m) }
func (*IncrAmountParam) ProtoMessage()    {}
func (*IncrAmountParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc2ddf47808c4d6, []int{2}
}

func (m *IncrAmountParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrAmountParam.Unmarshal(m, b)
}
func (m *IncrAmountParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrAmountParam.Marshal(b, m, deterministic)
}
func (m *IncrAmountParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrAmountParam.Merge(m, src)
}
func (m *IncrAmountParam) XXX_Size() int {
	return xxx_messageInfo_IncrAmountParam.Size(m)
}
func (m *IncrAmountParam) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrAmountParam.DiscardUnknown(m)
}

var xxx_messageInfo_IncrAmountParam proto.InternalMessageInfo

func (m *IncrAmountParam) GetAccount() *account.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *IncrAmountParam) GetIncrNum() int64 {
	if m != nil {
		return m.IncrNum
	}
	return 0
}

func (m *IncrAmountParam) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

type IncrAmountResult struct {
	ErrorCode            uint64                 `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Msg                  string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	TimeUnix             int64                  `protobuf:"varint,3,opt,name=time_unix,json=timeUnix,proto3" json:"time_unix,omitempty"`
	Data                 *IncrAmountResult_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *IncrAmountResult) Reset()         { *m = IncrAmountResult{} }
func (m *IncrAmountResult) String() string { return proto.CompactTextString(m) }
func (*IncrAmountResult) ProtoMessage()    {}
func (*IncrAmountResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc2ddf47808c4d6, []int{3}
}

func (m *IncrAmountResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrAmountResult.Unmarshal(m, b)
}
func (m *IncrAmountResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrAmountResult.Marshal(b, m, deterministic)
}
func (m *IncrAmountResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrAmountResult.Merge(m, src)
}
func (m *IncrAmountResult) XXX_Size() int {
	return xxx_messageInfo_IncrAmountResult.Size(m)
}
func (m *IncrAmountResult) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrAmountResult.DiscardUnknown(m)
}

var xxx_messageInfo_IncrAmountResult proto.InternalMessageInfo

func (m *IncrAmountResult) GetErrorCode() uint64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *IncrAmountResult) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *IncrAmountResult) GetTimeUnix() int64 {
	if m != nil {
		return m.TimeUnix
	}
	return 0
}

func (m *IncrAmountResult) GetData() *IncrAmountResult_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type IncrAmountResult_Data struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrAmountResult_Data) Reset()         { *m = IncrAmountResult_Data{} }
func (m *IncrAmountResult_Data) String() string { return proto.CompactTextString(m) }
func (*IncrAmountResult_Data) ProtoMessage()    {}
func (*IncrAmountResult_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbc2ddf47808c4d6, []int{3, 0}
}

func (m *IncrAmountResult_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrAmountResult_Data.Unmarshal(m, b)
}
func (m *IncrAmountResult_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrAmountResult_Data.Marshal(b, m, deterministic)
}
func (m *IncrAmountResult_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrAmountResult_Data.Merge(m, src)
}
func (m *IncrAmountResult_Data) XXX_Size() int {
	return xxx_messageInfo_IncrAmountResult_Data.Size(m)
}
func (m *IncrAmountResult_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrAmountResult_Data.DiscardUnknown(m)
}

var xxx_messageInfo_IncrAmountResult_Data proto.InternalMessageInfo

func (m *IncrAmountResult_Data) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountInfoParam)(nil), "cootek.pgd.base.account.AccountInfoParam")
	proto.RegisterType((*AccountInfoResult)(nil), "cootek.pgd.base.account.AccountInfoResult")
	proto.RegisterType((*AccountInfoResult_Data)(nil), "cootek.pgd.base.account.AccountInfoResult.Data")
	proto.RegisterType((*IncrAmountParam)(nil), "cootek.pgd.base.account.IncrAmountParam")
	proto.RegisterType((*IncrAmountResult)(nil), "cootek.pgd.base.account.IncrAmountResult")
	proto.RegisterType((*IncrAmountResult_Data)(nil), "cootek.pgd.base.account.IncrAmountResult.Data")
}

func init() { proto.RegisterFile("cootek.pgd.base.account.proto", fileDescriptor_dbc2ddf47808c4d6) }

var fileDescriptor_dbc2ddf47808c4d6 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x41, 0x4f, 0xea, 0x40,
	0x10, 0xc7, 0xe9, 0x6b, 0x1f, 0xd0, 0x79, 0x79, 0x79, 0xbc, 0x8d, 0xd1, 0x0a, 0x42, 0x48, 0x4f,
	0xc5, 0xc3, 0x36, 0xc1, 0x78, 0xf4, 0x00, 0x78, 0xe1, 0x42, 0xcc, 0x26, 0x5e, 0xbc, 0x34, 0xcb,
	0x76, 0x25, 0x0d, 0x76, 0x97, 0x94, 0xad, 0xc1, 0xef, 0xe7, 0xdd, 0x4f, 0xe1, 0xf7, 0x30, 0xdd,
	0x16, 0x29, 0x1a, 0x4c, 0x13, 0xe3, 0xad, 0x33, 0x9d, 0xff, 0xcc, 0x7f, 0x7e, 0x93, 0x85, 0x2e,
	0x93, 0x52, 0xf1, 0x25, 0x5e, 0x2d, 0x42, 0x3c, 0xa7, 0x6b, 0x8e, 0x29, 0x63, 0x32, 0x15, 0x0a,
	0xaf, 0x12, 0xa9, 0x24, 0x3a, 0x39, 0xf0, 0xbb, 0xfd, 0x77, 0xaf, 0xce, 0x9d, 0x42, 0x6b, 0x94,
	0x27, 0xa6, 0xe2, 0x5e, 0xde, 0xd0, 0x84, 0xc6, 0xe8, 0x12, 0x1a, 0x45, 0x91, 0x63, 0xf4, 0x0d,
	0xef, 0xcf, 0xb0, 0x83, 0x4b, 0xdd, 0xb6, 0xfa, 0x42, 0x46, 0xb6, 0xb5, 0xee, 0xab, 0x01, 0xff,
	0x4b, 0xbd, 0x08, 0x5f, 0xa7, 0x0f, 0x0a, 0x75, 0x01, 0x78, 0x92, 0xc8, 0x24, 0x60, 0x32, 0xe4,
	0xba, 0x9f, 0x45, 0x6c, 0x9d, 0x99, 0xc8, 0x90, 0xa3, 0x16, 0x98, 0xf1, 0x7a, 0xe1, 0xfc, 0xea,
	0x1b, 0x9e, 0x4d, 0xb2, 0x4f, 0xd4, 0x01, 0x5b, 0x45, 0x31, 0x0f, 0x52, 0x11, 0x6d, 0x1c, 0xb3,
	0x6f, 0x78, 0x26, 0x69, 0x66, 0x89, 0x5b, 0x11, 0x6d, 0xd0, 0x04, 0xac, 0x90, 0x2a, 0xea, 0x58,
	0xda, 0x97, 0x8f, 0x0f, 0x41, 0xf8, 0xe4, 0x03, 0x5f, 0x53, 0x45, 0x89, 0x16, 0xb7, 0xaf, 0xc0,
	0xca, 0x22, 0x74, 0x0c, 0x75, 0x1a, 0xbf, 0xaf, 0x69, 0x92, 0x22, 0xca, 0x2c, 0xab, 0x88, 0x2d,
	0xb9, 0x0a, 0x44, 0x1a, 0x6b, 0x6b, 0x26, 0xb1, 0xf3, 0xcc, 0x2c, 0x8d, 0xdd, 0x27, 0xf8, 0x37,
	0x15, 0x2c, 0x19, 0xe9, 0xe2, 0xef, 0x10, 0x43, 0xa7, 0xd0, 0x8c, 0x04, 0x4b, 0x4a, 0x63, 0x1a,
	0x59, 0x3c, 0x4b, 0x63, 0x74, 0x04, 0xbf, 0xf9, 0x23, 0x17, 0x4a, 0x13, 0xb0, 0x49, 0x1e, 0xb8,
	0xcf, 0x06, 0xb4, 0x76, 0xb3, 0x7f, 0x84, 0xf0, 0x78, 0x8f, 0x30, 0x3e, 0x48, 0xf8, 0xa3, 0x8d,
	0x32, 0xe0, 0xde, 0xd7, 0x80, 0x87, 0x2f, 0x06, 0x34, 0x0a, 0x18, 0x28, 0x00, 0x2b, 0xbb, 0x12,
	0x1a, 0x54, 0xb9, 0xa5, 0xa6, 0xdd, 0x3e, 0xaf, 0x7e, 0x76, 0xb7, 0x86, 0x18, 0xc0, 0xce, 0x2b,
	0xf2, 0x2a, 0x2c, 0x94, 0x4f, 0x19, 0x54, 0x5e, 0xdd, 0xad, 0x8d, 0x7b, 0x77, 0x67, 0x59, 0x89,
	0x9f, 0x4b, 0xfc, 0xd5, 0x22, 0xf4, 0x75, 0x5c, 0x48, 0xe6, 0x75, 0xfd, 0xda, 0x2e, 0xde, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x32, 0x1a, 0xe7, 0x53, 0xb6, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	Info(ctx context.Context, in *AccountInfoParam, opts ...grpc.CallOption) (*AccountInfoResult, error)
	IncrAmount(ctx context.Context, in *IncrAmountParam, opts ...grpc.CallOption) (*IncrAmountResult, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) Info(ctx context.Context, in *AccountInfoParam, opts ...grpc.CallOption) (*AccountInfoResult, error) {
	out := new(AccountInfoResult)
	err := c.cc.Invoke(ctx, "/cootek.pgd.base.account.Account/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) IncrAmount(ctx context.Context, in *IncrAmountParam, opts ...grpc.CallOption) (*IncrAmountResult, error) {
	out := new(IncrAmountResult)
	err := c.cc.Invoke(ctx, "/cootek.pgd.base.account.Account/IncrAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	Info(context.Context, *AccountInfoParam) (*AccountInfoResult, error)
	IncrAmount(context.Context, *IncrAmountParam) (*IncrAmountResult, error)
}

// UnimplementedAccountServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServer struct {
}

func (*UnimplementedAccountServer) Info(ctx context.Context, req *AccountInfoParam) (*AccountInfoResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (*UnimplementedAccountServer) IncrAmount(ctx context.Context, req *IncrAmountParam) (*IncrAmountResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrAmount not implemented")
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountInfoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cootek.pgd.base.account.Account/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Info(ctx, req.(*AccountInfoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_IncrAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrAmountParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).IncrAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cootek.pgd.base.account.Account/IncrAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).IncrAmount(ctx, req.(*IncrAmountParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cootek.pgd.base.account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Account_Info_Handler,
		},
		{
			MethodName: "IncrAmount",
			Handler:    _Account_IncrAmount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cootek.pgd.base.account.proto",
}
